namespace ContentManagementSystem.Data.Models.Cms;

/// <summary>
/// One derived encoding of a <see cref="MediaItem"/> at a particular size, mode, and format
/// (spec sections 13.5 and 23.3).
/// </summary>
/// <remarks>
/// Cache-like and entirely derived: every row here can be regenerated from the original bytes and
/// the spec that produced it, which is why renditions are excluded from backups and from the audit
/// interceptor (spec section 23.5). Losing the table costs CPU on the next request and nothing else.
/// <para>
/// Rows appear lazily. The delivery endpoint generates on first request behind a per-key semaphore
/// and persists the result, so twenty concurrent cold requests for one rendition produce one encode
/// rather than twenty (ADR 0007).
/// </para>
/// <para>
/// Plain <see cref="EntityBase"/> rather than <see cref="FingerPrintEntityBase"/>: these rows are
/// written by the pipeline, never by a person, so "who created this" has no answer worth storing.
/// </para>
/// </remarks>
public class MediaRendition : EntityBase
{
    /// <summary>Item this was derived from.</summary>
    public int MediaItemId { get; set; }

    /// <summary>Item this was derived from.</summary>
    public MediaItem MediaItem { get; set; } = null!;

    /// <summary>
    /// SHA-256 of the normalized <see cref="Spec"/>, carrying the uniqueness constraint.
    /// </summary>
    /// <remarks>
    /// The spec text is short enough to index directly, but hashing it makes the lookup key a fixed
    /// 32 bytes and — more usefully — forces every caller through the one normalization routine.
    /// Two spellings of the same rendition that hashed differently would each get their own encode
    /// and their own row, which is the failure this column exists to make impossible.
    /// </remarks>
    public byte[] SpecHash { get; set; } = null!;

    /// <summary>The normalized rendition spec this was generated from, kept readable for diagnostics.</summary>
    public string Spec { get; set; } = null!;

    /// <summary>Pixel width of the generated image.</summary>
    public int Width { get; set; }

    /// <summary>Pixel height of the generated image.</summary>
    public int Height { get; set; }

    /// <summary>Output format, such as <c>webp</c> or <c>jpeg</c>.</summary>
    public string Format { get; set; } = null!;

    /// <summary>Encoder quality the image was produced at.</summary>
    public int Quality { get; set; }

    /// <summary>Size of the generated file in bytes.</summary>
    public long SizeBytes { get; set; }

    /// <summary>Key the generated bytes are stored under in the media store.</summary>
    public string StorageKey { get; set; } = null!;

    /// <summary>
    /// The item's <see cref="MediaItem.EditsVersion"/> at the moment this was generated.
    /// </summary>
    /// <remarks>
    /// What makes a stale rendition recognisable. A library edit bumps the item's counter, so any
    /// row whose value is behind it was produced from superseded edits and must not be served — the
    /// signature would not validate for it anyway, since the version is part of what is signed.
    /// </remarks>
    public int EditsVersion { get; set; }

    /// <summary>When the encode happened.</summary>
    public DateTimeOffset GeneratedOn { get; set; }

    /// <summary>
    /// When this rendition was last served.
    /// </summary>
    /// <remarks>
    /// Updated lazily rather than on every hit: the point is to let a future eviction job find
    /// renditions nothing has asked for in months, and paying a write on every image request to
    /// keep that column exact would cost far more than the storage it reclaims.
    /// </remarks>
    public DateTimeOffset? LastAccessedOn { get; set; }
}
