<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContentManagementSystem.Data\ContentManagementSystem.Data.csproj" />
    <ProjectReference Include="..\ContentManagementSystem.Shared\ContentManagementSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
